config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "tasks", to: "tasks#index", as: :tasks
  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <div class="container py-3">
      <div class="row justify-content-center">
        <div class="col-6">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_area :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
<i class="fa-solid fa-clock-rotate-left"></i> <%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h2>All Tasks</h2>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        <%= link_to task.title, task_path(task) %>
        <%= link_to '<i class="fa-regular fa-trash-can"></i>'.html_safe, task_path(task), data: {turbo_method: :delete, turbo_confirm: "Delete " + task.title + "?"} %>
      </li>
  <% end %>
</ul>
<i class="fa-solid fa-plus"></i> <%= link_to "Add a new task", new_task_url %>

app/views/tasks/new.html.erb
<h2>New Task</h2>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_area :details %>
  <%= f.submit %>
<% end %>
<i class="fa-solid fa-clock-rotate-left"></i> <%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<div class="p-3 bg-secondary opacity-25 border border-2 rounded-2">
    <p class="details"><%= @task.details %></p>
</div>
<p><input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
<% if @task.completed %>
  <span>This task is completed</span>
<% else %>
  "This task is not completed yet"
<% end %>
<%= link_to "Edit this task", edit_task_url %>
<%= link_to "Back to list", tasks_path %>